package myapp.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;

/**
 * @Entity: Marks this class as a JPA entity, meaning it will be mapped to a database table.
 */
@Entity
public class WasteCategory {
    /**
     * @Id: Specifies the primary key of the entity.
     * @GeneratedValue(strategy = GenerationType.IDENTITY): Specifies that the primary key value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * @NotNull: Ensures that the name field cannot be null.
     */
    @NotNull
    private String name;

    public WasteCategory(long id, String name){
        this.id = id;
        this.name = name;
    }

    public WasteCategory(){}

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
